version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/
    overwrite: true
file_exists_behavior: OVERWRITE
branch_config:
    wip\/.*: ~
    main:
        deploymentGroupName: DK-DPG
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::975050379959:role/dk-role-code-deploy
